public class GeometryLabTest {

    public static void main (String[] args){
        GeometryLab fat = new GeometryLab();
        System.out.println(fat .f(2,3));
        System.out.println(fat .f(4,8));
        System.out.println(fat .g(3, 5));
        System.out.println(fat .g(5, 3));
        System.out.println(fat .h(2, 9));
        System.out.println(fat .h(4, 10));
        System.out.println(fat .j(5, 10));
        System.out.println(fat .j(10, 5));
        System.out.println(fat .k(9, 7));
        System.out.println(fat .k(7, 9));
        System.out.println(fat .m(3, 4, 5));
        System.out.println(fat .m(4, 6, 3));
        System.out.println(fat .f(fat.j(10, 5),fat .h(2, 9)));
        System.out.println(fat .g(fat.m(3, 4, 5),fat .h(4, 10)));
        System.out.println(fat .g(fat.j(5, 10),fat .f(2, 3)));
        System.out.println(fat .h(fat.m(4, 6, 3),fat .f(4, 8)));
        System.out.println(fat .h(fat.k(9, 7),fat .g(5, 3)));
        System.out.println(fat .j(fat.k(7, 9),fat .g(3, 5)));
        System.out.println(fat .j(fat.h(2, 9),fat .m(4, 6, 3)));
        System.out.println(fat .k(fat.m(3, 4, 5),fat .j(10, 5)));
        System.out.println(fat .k(fat.k(9, 7),fat .f(4, 8)));
        System.out.println(fat .m(fat.h(4, 10),fat .f(2, 3),fat .g(5, 3)));
        System.out.println(fat .m(fat.k(7, 9),fat .j(5, 10),fat .h(4, 10)));
        System.out.println(fat .triArea(2, 3));
        System.out.println(fat .triArea(4, 8));
        System.out.println(fat .trapArea(3, 4, 5));
        System.out.println(fat .trapArea(4, 6, 3));
        System.out.println(fat .rectArea(3, 5));
        System.out.println(fat .rectArea(5, 3));
        System.out.println(fat .circArea(7));
        System.out.println(fat .circArea(9));
        System.out.println(fat .paralArea(2, 9));
        System.out.println(fat .paralArea(4, 10));
        System.out.println(fat .pythHypotenuse(5, 10));
        System.out.println(fat .pythHypotenuse(9, 7));
        System.out.println(fat .triPrismVol(10, 5, 4));
        System.out.println(fat .triPrismVol(7, 9, 3));
        System.out.println(fat .rectPrismVol(2, 3, 4));
        System.out.println(fat .rectPrismVol(8, 3, 6));
        System.out.println(fat .rectPyramidVol(5, 7, 9));
        System.out.println(fat .rectPyramidVol(4, 6, 8));
        System.out.println(fat .cylVol(9, 2));
        System.out.println(fat .cylVol(10, 3));
        System.out.println(fat .sphereVol(6));
        System.out.println(fat .sphereVol(8));
        System.out.println(fat .coneVol(6, 5));
        System.out.println(fat .coneVol(8, 7));
        System.out.println(fat .sphereSurfArea(4));
        System.out.println(fat .sphereSurfArea(7));
        System.out.println(fat .cylSurfArea(4, 7));
        System.out.println(fat .cylSurfArea(5, 3));
        System.out.println(fat .rectPrismSurfArea(2, 3, 4));
        System.out.println(fat .rectPrismSurfArea(8, 3, 6));
        System.out.println(fat .triArea(fat .f(2, 3),fat . h(4, 8))); 
        System.out.println(fat .rectArea(fat .g(7, 5),fat . j(5, 3)));
        System.out.println(fat .trapArea(fat .m(3, 4, 5),fat . m(4, 6, 3),fat . m(8, 3, 6)));
        System.out.println(fat .circArea(fat .k(8, 5)));
        System.out.println(fat .paralArea(fat .j(9, 2),fat .f(4, 10)));
        System.out.println(fat .pythHypotenuse(fat .f(5, 10),fat . g(9, 7)));
        System.out.println(fat .triPrismVol(fat .m(10, 5, 4),fat . m(7, 9, 3),fat . m(5, 7, 3)));
        System.out.println(fat .rectPrismVol(fat .h(2, 4),fat . m(8, 3, 6),fat . h(3, 6)));
        System.out.println(fat .rectPyramidVol(fat .m(5, 7, 9),fat . m(4, 6, 8),fat .k(20, 7)));
        System.out.println(fat .cylVol(fat .h(9, 2),fat .k(10, 3)));
        System.out.println(fat .sphereVol(fat .g(9, 6)));
        System.out.println(fat .coneVol(fat .j(6, 5),fat . j(8, 7)));
        System.out.println(fat .sphereSurfArea(fat .m(4, 3, 1)));
        System.out.println(fat .cylSurfArea(4,fat . f(5, 3)));
        System.out.println(fat .rectPrismSurfArea(fat .pythHypotenuse(3, 4), 3,fat . k(13, 5)));
    }
}